repos:
-   repo: https://github.com/ambv/black
    rev: 24.4.0
    hooks:
    - id: black
      args:
          - --line-length=120
          - --exclude="""\.git |  
                \.__pycache__|  
                \.hg|  
                \.mypy_cache|  
                \.tox|  
                \.venv|  
                _build|  
                buck-out|  
                build|  
                dist"""
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --line-length=120
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --exclude="""\.git |  
            \.__pycache__|  
            \.hg|  
            \.mypy_cache|  
            \.tox|  
            \.venv|  
            _build|  
            buck-out|  
            build|  
            dist"""
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        exclude: ^(docs/|example-plugin/)

