"""inital

Revision ID: 1fc106da10e3
Revises: 
Create Date: 2024-09-10 00:03:09.139656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc106da10e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=127), nullable=True, comment='username'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, comment='deleted'))
    op.create_unique_constraint('user_items_username_unique', 'users', ['username'])
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.VARCHAR(length=127), autoincrement=False, nullable=True, comment='отчество'))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=127), autoincrement=False, nullable=True, comment='фамилия'))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=127), autoincrement=False, nullable=True, comment='имя'))
    op.drop_constraint('user_items_username_unique', 'users', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
